// Reviewed launch presets. Saved user choices always win; Restore settings uses
// these values. Quick actions are the existing buttons, never duplicate handlers.
export const toyTuning = {
  '073-holographic-shimmer': {
    quick: ['Level foil'],
    intensityLabel: 'Foil brightness',
    custom: { crinkle: 0.85, film: 3.5 },
    note: 'Readable rainbow folds with less noisy crinkling.',
  },
  '048-paint-pour-marble': {
    intensityLabel: 'Marble distortion',
    labels: { bands: 'Ring density' },
    custom: { bands: 2.2, lacing: 0.8 },
    note: 'Keep the visible Pour/Comb/Tilt selector; clearer paint bands.',
  },
  '045-slime-stretch': {
    speedLabel: 'Bead motion',
    labels: { cohesion: 'Gather strength' },
    custom: { cohesion: 1 },
    note: 'Preserve separate Scatter and Gather; no automatic reassembly.',
  },
  '025-voronoi-shift': {
    quick: ['Move cells', 'Split cells', 'Merge cells'],
    groups: [['Move cells', 'Split cells', 'Merge cells']],
    intensityLabel: 'Edge glow',
    labels: { border: 'Edge sharpness' },
    custom: { border: 65 },
    note: 'Expose all three editing modes; greater border value sharpens edges.',
  },
  '086-blackhole-accretion': {
    quick: ['Launch mode', 'View mode', 'Seed orbits'],
    groups: [['Launch mode', 'View mode']],
    intensityLabel: 'Disc glow',
    custom: { gravity: 0.09, inclination: 0.45 },
    note: 'Stable launchable orbits, easy camera mode and starter orbit button.',
  },
  '041-silk-cloth-ripple': {
    quick: ['Shake silk', 'Smooth fabric'],
    intensityControl: false,
    custom: { tension: 0.65, breeze: 0.18 },
    note: 'More compliant fabric and visible breeze; unused Light level removed.',
  },
  '070-fractal-tree-zoom': {
    quick: ['Grow a generation', 'Fit tree'],
    intensityLabel: 'Branch brightness',
    custom: { spread: 0.52, depth: 9, zoom: 1 },
    note: 'Keep readable branch targets and room for two more generations.',
  },
  '043-ink-fluid-art': {
    quick: ['Stir', 'Drop ink'],
    groups: [['Stir', 'Drop ink']],
    labels: { radius: 'Brush size', current: 'Background current' },
    custom: { radius: 11, viscosity: 1, current: 0.65, metallic: 0.9 },
    note: 'Broader local stirring; preserve metallic finish and gentle current.',
  },
  '044-soap-cutting': {
    quick: ['Shave a strip', 'Clear shavings'],
    custom: { depth: 0.04 },
    note: 'Visible curls on the first cut, with an accessible assisted shave.',
  },
  '047-playdoh-extruder': {
    quick: ['Press', 'Clear tray'],
    intensityLabel: 'Strand wobble',
    groups: [['Round die', 'Star die', 'Ribbon die']],
    note: 'Expose extrusion; keep the existing visible cutter and die options.',
  },
  '046-sand-mandala-rake': {
    quick: ['Comb', 'Smooth', 'Move stones', 'Undo'],
    groups: [['Comb', 'Single tine', 'Move stones', 'Smooth']],
    note: 'All essential gestures selectable without opening Tune.',
  },
  '049-bubble-wrap-pop': {
    quick: ['New sheet'],
    speedControl: false,
    note: 'Popping needs no tempo adjustment; sound stays opt-in and remembered.',
  },
  '053-stress-ball-squish': {
    automaticPlay: false,
    custom: { firmness: 1, recovery: 1.8 },
    note: 'Keep the strong squeeze; quicker recovery between presses. Remove rotation-only demo.',
  },
  '100-sensory-ball-ripple': {
    custom: { firmness: 0.85, waveSpeed: 2.6 },
    note: 'Softer poke response while retaining the successful ripple speed.',
  },
  '101-jelly-pal': {
    quick: ['Hop'],
    custom: { bounce: 0.45 },
    note: 'Slightly livelier bounce, with an obvious first action.',
  },
  '001-ceiling-fan': {
    quick: ['Motor on/off', 'Light on/off'],
    speedLabel: 'Motor speed',
    intensityLabel: 'Lamp brightness',
    labels: { friction: 'Coasting drag (motor off)' },
    custom: { friction: 0.25 },
    note: 'Motor and light states visible; longer hand-driven coast.',
  },
  '002-pinwheel': {
    quick: ['Send a breeze'],
    custom: { airDrag: 0.15 },
    note: 'A single swipe carries farther without requiring automatic play.',
  },
  '003-spinning-top': {
    quick: ['Launch'],
    custom: { friction: 0.15 },
    note: 'Longer satisfying spin, with relaunch always visible.',
  },
  '093-liquid-motion-timer': {
    quick: ['Flip timer'],
    custom: { fluidDrag: 1 },
    note: 'Clear flip action and slightly freer droplet movement.',
  },
  '094-fidget-spinner-blur': {
    quick: ['Brake'],
    intensityLabel: 'LED brightness',
    custom: { friction: 0.12 },
    note: 'Keep long coast and explicit brake; no extra automatic spin by default.',
  },
  '098-glitter-wand-tumble': {
    quick: ['Shake'],
    intensityLabel: 'Glitter sparkle',
    custom: { viscosity: 0.9 },
    note: 'Glitter follows a tilt more readily.',
  },
  '099-pendulum-fidget-swirl': {
    quick: ['Release a swing'],
    intensityLabel: 'Trail brightness',
    custom: { damping: 0.1 },
    note: 'Longer swings and one-tap launch.',
  },
  '032-koi-pond-ripples': {
    quick: ['Ripples', 'Move lily pads'],
    groups: [['Ripples', 'Move lily pads']],
    intensityLabel: 'Ripple visibility',
    note: 'Surface both distinct interactions; preserve current fish behavior.',
  },
  '102-bloom-brush': {
    quick: ['Vine', 'Fern', 'Meadow', 'Undo'],
    groups: [['Vine', 'Fern', 'Meadow']],
    note: 'Brushes and undo visible; preserve permanent artwork and growth settings.',
  },
  '060-glitter-snowglobe': {
    quick: ['Shake'],
    intensityLabel: 'Snow sparkle',
    labels: { snowfall: 'Snow settling speed' },
    custom: { snowfall: 0.9 },
    note: 'A little longer airborne; slider actually controls settling, not snow count.',
  },
  '056-lava-lamp': {
    quick: ['Warm wax', 'Cool wax'],
    intensityLabel: 'Lamp glow',
    custom: { heater: 1, viscosity: 1 },
    note: 'Keep the validated thermal cycle; expose heating and cooling.',
  },
  '065-plasma-ball': {
    intensityLabel: 'Arc brightness',
    labels: { branchiness: 'Arc waviness' },
    custom: { branchiness: 0.8 },
    note: 'Clearer converging filaments; slider bends arcs rather than adding branches.',
  },
  '071-flow-field-particles': {
    quick: ['Clear currents'],
    intensityLabel: 'Stream energy',
    custom: { persistence: 4, fieldScale: 0.0022 },
    note: 'User-made vortices linger; retain the readable stream scale.',
  },
  '091-lightning-branch-loop': {
    quick: ['Discharge', 'Arrange nodes'],
    intensityLabel: 'Bolt brightness',
    note: 'Show the discharge action; preserve reduced-flash default.',
  },
  '018-kaleidoscope': {
    quick: ['6 mirrors', '8 mirrors', '12 mirrors'],
    groups: [['4 mirrors', '6 mirrors', '8 mirrors', '12 mirrors']],
    active: ['8 mirrors'],
    intensityLabel: 'Glass sparkle',
    custom: { zoom: 3 },
    note: 'Expose symmetry presets without changing the proven magnification.',
  },
  '068-liquid-metal-metaball': {
    quick: ['Gather drops'],
    intensityLabel: 'Metal brightness',
    custom: { cohesion: 0.6, viscosity: 1.8 },
    note: 'Less drag makes clicks and stretching more apparent.',
  },
  '069-spirograph-loop': {
    quick: ['New ink layer', 'Motor: on', 'Undo'],
    groups: [['7 petals', '8 petals', '12 petals']],
    active: ['8 petals'],
    labels: { layerRotation: 'Rotation per layer' },
    custom: { reach: 0.75, inkWidth: 1.4, layerRotation: 7 },
    note: 'Keep continuous layers, improve line readability and expose drawing controls.',
  },
  '081-warp-speed-tunnel': {
    intensityControl: false,
    speedControl: false,
    labels: { cruise: 'Cruise speed' },
    custom: { cruise: 0.8, steering: 1.3 },
    note: 'Use dedicated cruise/steering controls, not three overlapping speed adjustments.',
  },
  '066-wireframe-morph': {
    quick: ['Rotate', 'Sculpt'],
    groups: [
      ['Rotate', 'Sculpt'],
      ['Sphere', 'Cube', 'Octahedron', 'Organic', 'Crystal'],
    ],
    intensityLabel: 'Wire glow',
    custom: { twistControl: 0 },
    note: 'Make sculpting discoverable; keep a clean recognizable starting shape.',
  },
  '063-neon-tunnel': {
    speedControl: false,
    quick: ['3 sides', '6 sides', '8 sides'],
    intensityLabel: 'Neon glow',
    custom: { travelSpeed: 1 },
    note: 'Dedicated Travel control replaces redundant generic Tempo.',
  },
  '015-prism-refraction': {
    intensityLabel: 'Beam brightness',
    labels: { dispersion: 'Spectrum width' },
    custom: { prismAngle: 0, dispersion: 0.7 },
    note: 'Wider spectrum by default; direct dragging must not be overwritten by the slider.',
  },
  '030-jellyfish-drift': {
    intensityLabel: 'Bioluminescence',
    custom: { currentStrength: 1.2, bellRhythm: 1 },
    note: 'A stronger response to swept currents, with the natural bell rhythm preserved.',
  },
}
